source 'https://rubygems.org'

gem 'activerecord', '~> 6.1'
gem 'sinatra-activerecord' # For adding custom rake db:* commands easily
gem 'sqlite3', '~> 1.4'
gem 'rake'
gem 'tty-prompt', '~> 0.22'
gem 'pry'
gem 'aws-sdk-s3'
gem 'rspotify'
