source 'https://rubygems.org'

gem 'activerecord'
gem 'sinatra-activerecord' # For adding custom rake db:* commands easily
gem 'sqlite3'
gem 'rake'
gem 'tty-prompt'
gem 'aws-sdk-s3'
gem 'aws-sdk-sns'

gem 'pry'
gem 'mocha'
