source 'https://rubygems.org'

ruby '3.0.2'

gem 'activerecord'
gem 'sinatra-activerecord' # For adding custom rake db:* commands easily
gem 'sqlite3'
gem 'rake'
gem 'tty-prompt'
gem 'aws-sdk-s3'
gem 'aws-sdk-sns'
gem 'nokogiri' # Ruby 3.x warning, AWS gem requires xml parser not noted in their dependencies

gem 'test-unit'
gem 'mocha'
gem 'pry'

gem 'pcloud_api'
