# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Update JPDB Stats

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      KEEP_DAILY_STUDY_TIME: 'true'
      JPDB_USERNAME: ${{ secrets.JPDB_USERNAME }}
      JPDB_PASSWORD: ${{ secrets.JPDB_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Generate new daily_study_time.csv
      run: bundle exec rake
    - name: Commit updated daily_study_time.csv file
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add daily_study_time.csv && git commit -m 'Update daily_study_time.csv' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
